package org.mipams.jpegtrust.entities.assertions.tfm;

import com.fasterxml.jackson.dataformat.cbor.databind.CBORMapper;
import org.mipams.jpegtrust.entities.assertions.Assertion;
import org.mipams.jumbf.entities.CborBox;
import org.mipams.jumbf.entities.JumbfBox;
import org.mipams.jumbf.entities.JumbfBoxBuilder;
import org.mipams.jumbf.services.content_types.CborContentType;
import org.mipams.jumbf.util.MipamsException;
import org.mipams.jpegtrust.entities.assertions.CborAssertion;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * C2PA {@code c2pa.ai-disclosure} assertion (spec §18.28 / §18.29).
 *
 * <p>This assertion provides machine-readable AI-transparency information that
 * complements {@code digitalSourceType} in the actions assertion.  While
 * {@code digitalSourceType} describes <em>what kind of source</em> produced the
 * asset, {@code c2pa.ai-disclosure} discloses <em>how</em> it was produced,
 * including the specific model used, the degree of human involvement, and the
 * scientific domain classification.
 *
 * <h3>Mandatory field (C2PA §18.28.1.1)</h3>
 * <ul>
 *   <li>{@code modelType} — the broad category of generative model
 *       (e.g. {@code "diffusion"}, {@code "llm"}, {@code "gan"}, …).</li>
 * </ul>
 *
 * <h3>Optional fields (populate wherever information is available)</h3>
 * <ul>
 *   <li>{@code modelName} — human-readable model name.</li>
 *   <li>{@code modelIdentifier} — canonical URI / URL for the model.</li>
 *   <li>{@code contentProfile.humanOversightLevel} — one of:
 *       {@code "fully_autonomous"}, {@code "prompt_guided"},
 *       {@code "human_validated"}.
 *       See §18.29 Table 3 for the interplay with {@code digitalSourceType}.</li>
 *   <li>{@code scientificDomain} — list of arXiv taxonomy codes
 *       (e.g. {@code ["cs.AI", "cs.CV"]}).</li>
 * </ul>
 *
 * <h3>Relationship with {@code digitalSourceType} (C2PA §18.29 Table 3)</h3>
 * <pre>
 *  digitalSourceType                    humanOversightLevel   Interpretation
 *  ──────────────────────────────────── ───────────────────── ──────────────────────────────────────────────
 *  trainedAlgorithmicMedia              fully_autonomous      Pure AI; no human review.
 *  trainedAlgorithmicMedia              prompt_guided         AI guided by human prompt; moderate involvement.
 *  compositeWithTrainedAlgorithmicMedia human_validated       AI edits reviewed/approved by a human editor.
 *  digitalCreation                      (not applicable)      No trained model; assertion is not attached.
 * </pre>
 *
 * <h3>JUMBF structure (CborContentType)</h3>
 * <pre>
 *  JumbfBox  (label = "c2pa.assertions/c2pa.ai-disclosure")
 *    └── CborBox  (CBOR-encoded ai-disclosure-map)
 * </pre>
 *
 * <h3>Serialised CBOR schema (§18.29.1)</h3>
 * <pre>
 *  ai-disclosure-map = {
 *      "modelType"          : tstr,                   ; MANDATORY
 *    ? "modelName"          : tstr,
 *    ? "modelIdentifier"    : tstr,                   ; URI
 *    ? "contentProfile"     : content-profile-map,
 *    ? "scientificDomain"   : [+ tstr],               ; arXiv codes
 *  }
 *
 *  content-profile-map = {
 *    ? "humanOversightLevel" : $human-oversight-level-choice,
 *  }
 *
 *  $human-oversight-level-choice /= "fully_autonomous"
 *  $human-oversight-level-choice /= "prompt_guided"
 *  $human-oversight-level-choice /= "human_validated"
 * </pre>
 *
 * <h3>Usage example</h3>
 * <pre>{@code
 * AiDisclosureAssertion ai = new AiDisclosureAssertion();
 * ai.setModelType("diffusion");
 * ai.setModelName("Fooocus 2.5.0");
 * ai.setModelIdentifier("https://github.com/lllyasviel/Fooocus");
 * ai.setHumanOversightLevel(AiDisclosureAssertion.HumanOversightLevel.PROMPT_GUIDED);
 * ai.setScientificDomain(List.of("cs.AI", "cs.CV"));
 *
 * JumbfBox box = ai.toJumbfBox();
 * }</pre>
 */
public class AiDisclosureAssertion extends CborAssertion {

    // ------------------------------------------------------------------
    // Nested enum — human oversight level choices (C2PA §18.29)
    // ------------------------------------------------------------------

    /**
     * The degree of human involvement in the generation pipeline.
     * Maps directly to the {@code humanOversightLevel} field values defined
     * in C2PA §18.29.
     */
    public enum HumanOversightLevel {
        /** Asset generated autonomously; no human review took place. */
        FULLY_AUTONOMOUS("fully_autonomous"),

        /**
         * Asset generated by a model steered by a human-supplied prompt;
         * moderate human involvement.  Pair with
         * {@code trainedAlgorithmicMedia} in {@code digitalSourceType}.
         */
        PROMPT_GUIDED("prompt_guided"),

        /**
         * AI edits were applied and reviewed or approved by a human editor
         * before release.  Pair with
         * {@code compositeWithTrainedAlgorithmicMedia}.
         */
        HUMAN_VALIDATED("human_validated");

        private final String value;

        HumanOversightLevel(String value) {
            this.value = value;
        }

        /** Returns the string value as it appears in the CBOR payload. */
        public String getValue() {
            return value;
        }
    }

    // ------------------------------------------------------------------
    // Fields
    // ------------------------------------------------------------------

    /** MANDATORY — broad category of the generative model. */
    private String modelType;

    /** Human-readable model name (optional). */
    private String modelName;

    /** Canonical URI / URL for the model (optional). */
    private String modelIdentifier;

    /**
     * Structured signal of human involvement in the generation pipeline
     * (optional, but strongly recommended when information is available).
     */
    private HumanOversightLevel humanOversightLevel;

    /**
     * List of arXiv taxonomy codes that characterise the scientific domain
     * of the content (optional).  Examples: {@code "cs.AI"}, {@code "cs.CV"}.
     */
    private List<String> scientificDomain;

    // ------------------------------------------------------------------
    // Assertion interface
    // ------------------------------------------------------------------
    private String label = getDefaultLabel();
    
    public String getDefaultLabel() {
        return "c2pa.ai-disclosure";
    }
    @Override
    public String getLabel() {
        return label;
    }
    public void setLabel(String label) {
        this.label = label;
    }

    @Override
    public boolean isReductable() throws MipamsException {
        return true;
    }
    // ------------------------------------------------------------------
    // Getters & setters
    // ------------------------------------------------------------------

    public String getModelType() { return modelType; }

    /**
     * Sets the broad model category.  Mandatory.
     *
     * @param modelType e.g. {@code "diffusion"}, {@code "llm"}, {@code "gan"}.
     */
    public void setModelType(String modelType) { this.modelType = modelType; }

    public String getModelName() { return modelName; }
    public void setModelName(String modelName) { this.modelName = modelName; }

    public String getModelIdentifier() { return modelIdentifier; }
    public void setModelIdentifier(String modelIdentifier) {
        this.modelIdentifier = modelIdentifier;
    }

    public HumanOversightLevel getHumanOversightLevel() { return humanOversightLevel; }

    /**
     * Sets the human oversight level.
     *
     * <p>Choose the value that correctly reflects the degree of human
     * involvement, and ensure it is consistent with the {@code digitalSourceType}
     * value on the {@code c2pa.created} action (see C2PA §18.29 Table 3).
     */
    public void setHumanOversightLevel(HumanOversightLevel humanOversightLevel) {
        this.humanOversightLevel = humanOversightLevel;
    }

    public List<String> getScientificDomain() { return scientificDomain; }

    /**
     * Sets the arXiv taxonomy codes for the content's scientific domain.
     *
     * @param scientificDomain e.g. {@code List.of("cs.AI", "cs.CV")}.
     */
    public void setScientificDomain(List<String> scientificDomain) {
        this.scientificDomain = scientificDomain;
    }
}